server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  datasource:
    url: jdbc:mysql://193.112.94.161:3306/spring-boot-demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: JiangKai@Password123
    driver-class-name: com.mysql.cj.jdbc.Driver
